### ISSUE TITLE
re-captcha on stockbit

### ISSUE THREAD

**Issue by kaederukawa7** [noczero/idx-fundamental-analysis#1]
login tidak berhasil (stockbit)
error : Error: Received status code 400 - {"message":"Username atau password harus di-isi.","error_type":"BAD_REQUEST"}

padahal sebelumnya berjalan lancar . namun tiba2 error tersebut.

**Comment by noczero** [comment]
Hey @kaederukawa7,

Thanks for reporting the authorization issue with Stockbit. It appears they've updated their login API and now require captcha verification.

I found an alternative endpoint: `https://api.stockbit.com/v2.5/login`, and it seems to be working for now.

I've deployed the fix and added some improvements, hope it helps!

**Comment by kaederukawa7** [comment]
thx so much....

**Comment by kaederukawa7** [comment]
> Hey [@kaederukawa7](https://github.com/kaederukawa7),
> 
> Thanks for reporting the authorization issue with Stockbit. It appears they've updated their login API and now require captcha verification.
> 
> I found an alternative endpoint: `https://api.stockbit.com/v2.5/login`, and it seems to be working for now.
> 
> I've deployed the fix and added some improvements, hope it helps!

it looks like the problem is back
{'message': 'ReCAPTCHA validation failed. Please try again.', 'error_type': 'INVALID_RECAPTCHA'}
